version: "3.1"
services:
  fantom:
    build:
      args:
        VERSION: release/1.1.0-rc.4
      context: ./fantom
      dockerfile: Dockerfile
    environment:
      - SNAPSHOT_URL=https://download.fantom.network/opera_5may22.tgz
    volumes:
      - "fantom:/datadir"
    expose:
      - "18545"
    networks:
      - chains
    restart: unless-stopped
    labels:

volumes:
  fantom:
